[package]
name = "trac"
version = "0.1.0"
authors = ["David H. R. Clymer <david@zettazebra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10"
xmlrpc = "0.14"
